In [10]:
import numpy as np
import pandas as pd
from q_1_1 import LassoRegression
from q_1_2 import RidgeRegression

In [2]:
dataSet=pd.read_csv('../input_data/data.csv').drop(['Serial No.'],axis=1)

In [3]:
trainingData=dataSet.sample(frac=0.8,random_state=100)
validationData=dataSet.drop(trainingData.index)
trainingLabel=trainingData.pop('Chance of Admit ')
validationLabel=validationData.pop('Chance of Admit ')

In [4]:
X_Train=np.array(trainingData)
X_Train=(X_Train-X_Train.mean(axis=0))/X_Train.std(axis=0)
Y_Train=np.array(trainingLabel).reshape((len(trainingLabel),1))

X_Test=np.array(validationData)
X_Test=(X_Test-X_Test.mean(axis=0))/X_Test.std(axis=0)
Y_Test=np.array(validationLabel).reshape((len(validationLabel),1))

In [5]:
RidgeModel=RidgeRegression(alpha=0.1,lamda=5,epochs=1000)
RidgeModel.fit(X_Train,Y_Train)

LassoModel=LassoRegression(alpha=0.1,lamda=5,epochs=1000)
LassoModel.fit(X_Train,Y_Train)

In [6]:
thetaR=RidgeModel.theta
thetaL=LassoModel.theta
diffTheta=thetaR-thetaL

In [7]:
print("Weights of Ridge Regression:\n",thetaR)
print("Weights of Lasso Regression:\n",thetaL)
print("Weight difference b/w Ridge & Lasso:\n",diffTheta)

Weights of Ridge Regression:
 [[0.02045847]
 [0.01820959]
 [0.00897317]
 [0.00417868]
 [0.01686292]
 [0.06628734]
 [0.01490073]]
Weights of Lasso Regression:
 [[0.01770614]
 [0.01360849]
 [0.00482471]
 [0.00178719]
 [0.0116344 ]
 [0.07129059]
 [0.00716781]]
Weight difference b/w Ridge & Lasso:
 [[ 0.00275233]
 [ 0.0046011 ]
 [ 0.00414846]
 [ 0.00239149]
 [ 0.00522852]
 [-0.00500325]
 [ 0.00773292]]


In [8]:
print("Error on Ridge Regression:",RidgeModel.MSE(X_Test,Y_Test))

Error on Ridge Regression: 0.0020437283276922838


In [9]:
print("Error on Lasso Regression:",LassoModel.MSE(X_Test,Y_Test))

Error on Lasso Regression: 0.0018766387839987179
